# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: local-selfsigned-root
#   namespace: cert-manager
# spec:
#   selfSigned: {}

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: local-root-ca
#   namespace: cert-manager
# spec:
#   isCA: true
#   commonName: "Lungo Local Root CA"
#   secretName: local-root-ca
#   duration: 87600h
#   privateKey: { algorithm: RSA, size: 2048 }
#   issuerRef: { name: local-selfsigned-root, kind: Issuer }
