apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app:  {{ .Values.appName }}
spec:
  {{- if eq.Values.environment "local"}}
  type: NodePort
  {{- end}}
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app:  {{ .Values.appName }}