apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  ENABLE_HTTP: "{{ .Values.config.enableHttp }}"
  MCP_CONNECTION_MODE: "{{ .Values.config.mcpConnectionMode }}"
  DIRECTORY_CLIENT_SERVER_ADDRESS: "{{ .Values.config.directoryClientServerAddress }}"
  DIRECTORY_CLIENT_TLS_SKIP_VERIFY: "{{ .Values.config.directoryClientTlsSkipVerify }}"
  OASF_API_VALIDATION_SCHEMA_URL: "{{ .Values.config.oasfApiValidationSchemaUrl }}"
  LLM_MODEL: "{{ .Values.config.llmModel }}"
  AZURE_API_BASE: "{{ .Values.config.azureApiBase }}"
  AZURE_API_VERSION: "{{ .Values.config.azureApiVersion }}"
  DEFAULT_MESSAGE_TRANSPORT: "{{ .Values.config.defaultMessageTransport }}"
  TRANSPORT_SERVER_ENDPOINT: "{{ .Values.config.transportServerEndpoint }}"
  OTLP_HTTP_ENDPOINT: "{{ .Values.config.otlpHttpEndpoint }}"
