apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  AZURE_OPENAI_ENDPOINT: "{{ .Values.config.azureOpenAiEndpoint }}"
  AZURE_OPENAI_DEPLOYMENT: "{{ .Values.config.azureOpenAiDeployment }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.config.azureOpenAiApiVersion }}"
  OPENAI_API_KEY: "{{ .Values.config.openAiApiKey }}"
  OPENAI_ENDPOINT: "{{ .Values.config.openAiEndpoint }}"
  OPENAI_MODEL_NAME: "{{ .Values.config.openAiModelName }}"
  LLM_PROVIDER: "{{ .Values.config.llmProvider }}"
  TRANSPORT_SERVER_ENDPOINT: "{{ .Values.config.transportServerEndpoint }}"
  DEFAULT_MESSAGE_TRANSPORT: "{{ .Values.config.defaultMessageTransport }}"
  OTLP_HTTP_ENDPOINT: "{{ .Values.config.otlpHttpEndpoint }}"
  LLM_STREAMING: "{{ .Values.config.llmStreaming }}"
  EXPERIMENTAL_FEATURE: "{{ .Values.config.experimentalFeature }}"
